### ISSUE TITLE
create multiline graph with expression in Pivot config.yaml

### ISSUE THREAD

**Issue by satanworker** [implydata/plywood#128]
Hello!

I really need to understand if its possible to aggregate few measures into one multiline graph by expression in config.yaml of my Pivot? it appears to be Plywood expression so writing question here.

So I have those 2 dimensions, like "dimension1" and "dimension2", and I need something like: 
     - name: combine
        title: Combine
        formula: [$main.sum($dimension1), $main.sum($dimension2)]

Thanks in advance!

**Comment by vogievetsky** [comment]
An aggregate (such as sum) in plywood returns a single number. As for how plywood is used in Pivot: that is outside of the scope of this issue. See https://github.com/implydata/pivot/issues/322
