### ISSUE TITLE
test.html doesn't seem to contain valid code

### ISSUE THREAD

**Issue by Crystark** [implydata/plywood#32]
Hi,

I'm trying to understand and play with plywood so I tried the `test.html` file but i'm getting the following error right away:

```
Uncaught TypeError: name must be a string$ @ plywood.js:4788(anonymous function) @ test.html:27
```

This seems to come from `$()` as it has no param.

**Comment by Crystark** [comment]
Actually that code seems completely outdated.
I've replace `$()` by `ply()`, fixed the `=` with `==` and am currently struggling with the removal of `mark` that i can't find an alternative to (mostly cause i currently do not understand exactly what it did and what it can be replaced with)

**Comment by vogievetsky** [comment]
O woops, that file is totally out of date and should not have been committed in the first place.

If you want to play with plywood the up-to-date code lives in the /docs directory.

Also you can see it rendered here: plywood.imply.io/gallery

Going to delete test.html (closing issue). Sorry for the confusion.
