### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by xcoderzach** [implydata/plywood#38]
Are there any plans to add support for postgres (and redshift) style sql?  If you think this is something you would like to support I'd be happy to try my hand at a PR.

**Comment by vogievetsky** [comment]
Hi @xcoderzach,

Definitely interested in PG support.
There have been recent changes that should be helpful:

As of a few days ago Plywood runs all functional DB tests agains docker containers: https://github.com/implydata/plywood/blob/master/data/README.md

That hold the 'golden dataset' i.e. a standardized dataset that has a bunch of interesting features that need testing and facilitate cross database testing: (https://github.com/implydata/plywood/blob/master/test/functional/crossFunctional.mocha.js) a single query gets run on several databases with the same data and the results are expected to match.

What needs to be done to add PG support would be:

1. To create instructions and scripts for loading https://hub.docker.com/_/postgres/ and then loading it with the wikipedia dataset (i.e. extend https://github.com/implydata/plywood/blob/master/data/README.md)
2. To create a postgress requester (like https://github.com/implydata/plywood-mysql-requester by for PG) 
that is simply a wrapper around whatever library there is to provide a consistent interface.
3. To implement a PG external. I think this would be fairly easy considering the new tests.

There steps would need to be done in order. If you are interested to help LMK :-)

**Comment by vogievetsky** [comment]
Postgres is in! 🎆
