### ISSUE TITLE
Add quantile support

### ISSUE THREAD

**Issue by dclim** [implydata/plywood#8]
![screen shot 2015-10-28 at 3 54 51 pm](https://cloud.githubusercontent.com/assets/11050882/10805723/a364ab20-7d95-11e5-825a-0fb116bcb386.png)

**Comment by vogievetsky** [comment]
Ok, this is finally coming soon.

**Comment by vogievetsky** [comment]
This has been completed in the latest plywood.

**Comment by curran** [comment]
Sweet!
